CREATE TABLE circo_composition(
   circo TEXT,
   DEP TEXT,
   libdep TEXT,
   REG TEXT,
   libreg TEXT,
   COMMUNE_RESID TEXT,
   LIBcom TEXT,
   type_com TEXT,
   date_collecte TEXT
);

CREATE TABLE crimes_communes_2022(
   code_insee TEXT,
   date_crime TEXT,
   classe TEXT,
   unite_de_compte TEXT,
   valeur_publiee VARTEXT,
   tauxpourmille REAL,
   complementinfoval REAL,
   complementinfotaux REAL,
   date_collecte TEXT
);

CREATE TABLE famile_TAUX_CHOMAGE_valeurs_trimestrielles(
   idBank TEXT,
   Libelle TEXT,
   Derniere_mise_a_jour TEXT,
   annee TEXT,
   timestre TEXT,
   taux TEXT,
   date_collecte TEXT,
   PRIMARY KEY(idBank, annee, timestre)
);

CREATE TABLE indic_stat_circonscriptions_legislatives_2022(
   circo TEXT,
   Nom_de_la_circonscription VARCHAR(200),
   Inscrit_22 INTEGER,
   pop_legal_19 INTEGER,
   pop_legal_13 INTEGER,
   tvar_pop REAL,
   pop_pole_aav REAL,
   pop_cour_aav REAL,
   pop_horsaav REAL,
   pop_urb REAL,
   pop_rur_periu REAL,
   pop_rur_non_periu REAL,
   age_moyen REAL,
   dec90 INTEGER,
   dec75 INTEGER,
   dec50 INTEGER,
   dec25 INTEGER,
   dec10 INTEGER,
   actemp REAL,
   actcho REAL,
   inactret REAL,
   inactetu REAL,
   inactm14 REAL,
   inactaut REAL,
   actemp_hom REAL,
   actcho_hom REAL,
   inactret_hom REAL,
   inactetu_hom REAL,
   inactm14_hom REAL,
   inactaut_hom REAL,
   actemp_fem REAL,
   actcho_fem REAL,
   inactret_fem REAL,
   inactetu_fem REAL,
   inactm14_fem REAL,
   inactaut_fem REAL,
   actdip_PEU REAL,
   actdip_CAP REAL,
   actdip_BAC REAL,
   actdip_BAC2 REAL,
   actdip_BAC3 REAL,
   actdip_BAC5 REAL,
   actdip_BAC3P REAL,
   act_agr REAL,
   act_art REAL,
   act_cad REAL,
   act_int REAL,
   act_emp REAL,
   act_ouv REAL,
   act_cho REAL,
   log_res REAL,
   log_sec REAL,
   log_vac REAL,
   proprio REAL,
   locatai REAL,
   gratuit REAL,
   maison REAL,
   ach90 REAL,
   mfuel REAL,
   men_seul REAL,
   men_coupae REAL,
   men_coupse REAL,
   men_monop REAL,
   men_sfam REAL,
   men_seul_com REAL,
   men_coupse_com REAL,
   men_coupae_com REAL,
   men_monop_com REAL,
   men_complexe_com REAL,
   seul_hom1829 REAL,
   seul_hom3059 REAL,
   seul_hom6074 REAL,
   seul_hom7584 REAL,
   seul_hom85 REAL,
   seul_fem1829 REAL,
   seul_fem3059 REAL,
   seul_fem6074 REAL,
   seul_fem7584 REAL,
   seul_fem85 REAL,
   iranr_log REAL,
   iranr_com REAL,
   iranr_dep REAL,
   iranr_fra REAL,
   iranr_etr REAL,
   mobresid REAL,
   ilt_com REAL,
   ilt_dep REAL,
   ilt_fra REAL,
   ilt_etr REAL,
   mobtrav REAL,
   modtrans_aucun REAL,
   modtrans_pied REAL,
   modtrans_velo REAL,
   modtrans_moto REAL,
   modtrans_voit REAL,
   modtrans_commun REAL,
   tx_pauvrete60_diff REAL,
   nivvie_median_diff REAL,
   part_pauvres_diff REAL,
   part_modestes_diff REAL,
   part_medians_diff REAL,
   part_plutot_aises_diff REAL,
   part_aises_diff REAL,
   D1_diff INTEGER,
   D9_diff INTEGER,
   rpt_D9_D1_diff REAL,
   tx_pauvrete60_diff_trageRF1 REAL,
   tx_pauvrete60_diff_trageRF2 REAL,
   tx_pauvrete60_diff_trageRF3 REAL,
   tx_pauvrete60_diff_trageRF4 REAL,
   tx_pauvrete60_diff_trageRF5 REAL,
   tx_pauvrete60_diff_trageRF6 REAL,
   PACT REAL,
   PPEN REAL,
   PPAT REAL,
   PPSOC REAL,
   PIMPOT REAL,
   acc_ecole REAL,
   acc_college REAL,
   acc_lycee REAL,
   acc_medecin REAL,
   acc_dentiste REAL,
   acc_pharmacie REAL,
   part_eloig REAL,
   date_collecte TEXT,
   PRIMARY KEY(circo)
);

CREATE TABLE presidentielle_2022_communes_t1(
   code_departement TEXT,
   libelle_departement TEXT,
   code_commune TEXT,
   libelle_commune TEXT,
   prenom TEXT,
   nom TEXT,
   voix INTEGEREGER NOT NULL,
   date_election TEXT,
   date_collecte TEXT,
   PRIMARY KEY(code_departement, code_commune, prenom, nom)
);


CREATE TABLE resultats_par_niveau_subcom_t2_france_entiere_commun(
   Code_du_departement TEXT,
   Code_de_la_commune TEXT,
   Libelle_du_departement TEXT,
   Libelle_de_la_commune TEXT,
   Etat_saisie TEXT,
   Inscrits INTEGER,
   Abstentions INTEGER,
   _Abs_Ins REAL,
   Votants INTEGER,
   _Vot_Ins REAL,
   Blancs INTEGER,
   _Blancs_Ins REAL,
   _Blancs_Vot REAL,
   Nuls INTEGER,
   _Nuls_Ins REAL,
   _Nuls_Vot REAL,
   Exprimes INTEGER,
   _Exp_Ins REAL,
   _Exp_Vot REAL,
   date_collecte TEXT
);

CREATE TABLE resultats_par_niveau_subcom_t2_france_entiere_candidat(
   N_Panneau INTEGER,
   Sexe TEXT,
   Nom TEXT,
   Prenom TEXT,
   Voix INTEGER,
   _Voix_Ins REAL,
   _Voix_Exp REAL,
   Code_du_departement TEXT NOT NULL,
   Code_de_la_commune TEXT NOT NULL,
   FOREIGN KEY(Code_du_departement, Code_de_la_commune) REFERENCES resultats_par_niveau_subcom_t2_france_entiere_commun(Code_du_département, Code_de_la_commune)
);
